/*
    Copyright (c) 2016 Edouard M. Griffiths.  All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.
    * Neither the name of CM256 nor the names of its contributors may be
      used to endorse or promote products derived from this software without
      specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
    ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
    LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
    CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
*/

#include <iostream>
#include <fstream>
#include <string>
#include <getopt.h>

#include "mainutils.h"
#include "../cm256.h"

static bool example0(const std::string& filename, const std::string& refFilename)
{
#pragma pack(push, 1)
    struct Sample
    {
        uint16_t i;
        uint16_t q;
    };
    struct Header
    {
        uint16_t frameIndex;
        uint8_t  blockIndex;
        uint8_t  filler;
    };

    static const int samplesPerBlock = (512 - sizeof(Header)) / sizeof(Sample);

    struct ProtectedBlock
    {
        Sample samples[samplesPerBlock];
    };
    struct SuperBlock
    {
        Header         header;
        ProtectedBlock protectedBlock;
    };

    struct FileHeader
    {
        cm256_encoder_params m_cm256Params;
        int m_txBlocks;
    };
#pragma pack(pop)

    if (cm256_init())
    {
        return false;
    }

    cm256_encoder_params params;

    // Number of bytes per file block
    params.BlockBytes = sizeof(ProtectedBlock);

    // Number of blocks
    params.OriginalCount = 128;  // Superframe = set of protected frames

    // Number of additional recovery blocks generated by encoder
    params.RecoveryCount = 25;

    SuperBlock txBuffer[256];
    ProtectedBlock txRecovery[256];
    cm256_block txDescriptorBlocks[256];
    int frameCount = 0;

    // Fill original data
    for (int i = 0; i < params.OriginalCount+params.RecoveryCount; ++i)
    {
        txBuffer[i].header.frameIndex = frameCount;
        txBuffer[i].header.blockIndex = i;
        txDescriptorBlocks[i].Block = (void *) &txBuffer[i].protectedBlock;
        txDescriptorBlocks[i].Index = txBuffer[i].header.blockIndex;

        if (i < params.OriginalCount)
        {
            for (int k = 0; k < samplesPerBlock; k++)
            {
                txBuffer[i].protectedBlock.samples[k].i = rand();
                txBuffer[i].protectedBlock.samples[k].q = rand();
            }
        }
        else
        {
            memset((void *) &txBuffer[i].protectedBlock, 0, sizeof(ProtectedBlock));
        }

    }

    // Generate recovery data

    long long ts = getUSecs();

    if (cm256_encode(params, txDescriptorBlocks, txRecovery))
    {
        std::cerr << "example2: encode failed" << std::endl;
        return false;
    }

    long long usecs = getUSecs() - ts;

    std::cerr << "Encoded in " << usecs << " microseconds" << std::endl;

    // insert recovery data in sent data
    for (int i = 0; i < params.RecoveryCount; i++)
    {
        txBuffer[params.OriginalCount+i].protectedBlock = txRecovery[i];
    }

    // puncture blocks to simulate data loss

    SuperBlock* txFileBuffer = new SuperBlock[256]; // received blocks
    int nbTxFileBlocks = 0;

    for (int i = 0; i < params.OriginalCount+params.RecoveryCount; i++)
    {
        if (i % 6 != 4)
        //if (i != 101)
        {
            txFileBuffer[nbTxFileBlocks] = txBuffer[i];
            nbTxFileBlocks++;
        }
    }

    FileHeader fileHeader;
    fileHeader.m_cm256Params = params;
    fileHeader.m_txBlocks = nbTxFileBlocks;

    std::ofstream txFile;
    txFile.open(filename.c_str(), std::ios::out | std::ios::binary);

    txFile.write((const char *) &fileHeader, sizeof(FileHeader));

    for (int i = 0; i < nbTxFileBlocks; i++)
    {
        txFile.write((const char *) &txFileBuffer[i], sizeof(SuperBlock));
    }

    txFile.close();

    // reference

    std::ofstream refFile;
    refFile.open(refFilename.c_str(), std::ios::out | std::ios::binary);

    refFile.write((const char *) &fileHeader, sizeof(FileHeader));

    for (int i = 0; i < params.OriginalCount+params.RecoveryCount; i++)
    {
        refFile.write((const char *) &txBuffer[i], sizeof(SuperBlock));
    }

    refFile.close();

    return true;
}

static void usage()
{
    fprintf(stderr,
    "Usage: cm256_tx [options]\n"
    "\n"
    "  -c case        Test case index\n"
    "     - 0: file test:\n"
    "  -f file        test file\n"
    "  -r ref_file    reference file\n"
    "     - 1: UDP test:\n"
    "  -I address     IP address. Samples are sent to this address (default: 127.0.0.1)\n"
    "  -p port        Data port. Samples are sent on this UDP port (default 9090)\n"
    "\n");
}

int main(int argc, char *argv[])
{
    int testCaseIndex = 0;
    std::string dataaddress("127.0.0.1");
    int dataport = 9090;
    std::string filename("cm256.test");
    std::string refFilename("cm256.ref.test");

    const struct option longopts[] = {
        { "case",       1, NULL, 'c' },
        { "daddress",   2, NULL, 'I' },
        { "dport",      1, NULL, 'P' },
        { "file",       2, NULL, 'f' },
        { "reffile",    2, NULL, 'r' },
        { NULL,         0, NULL, 0 } };

    int c, longindex, value;
    while ((c = getopt_long(argc, argv,
            "c:I:P:f:r:",
            longopts, &longindex)) >= 0)
    {
        switch (c)
        {
        case 'c':
            if (!parse_int(optarg, value) || (value < 0) || (value > 1))
            {
                usage();
                badarg("-b");
                exit(1);
            }
            else
            {
                testCaseIndex = value;
            }
            break;
        case 'I':
            dataaddress.assign(optarg);
            break;
        case 'P':
            if (!parse_int(optarg, value) || (value < 0))
            {
                usage();
                badarg("-P");
                exit(1);
            }
            else
            {
                dataport = value;
            }
            break;
        case 'f':
            filename.assign(optarg);
            break;
        case 'r':
            refFilename.assign(optarg);
            break;
        default:
            usage();
            fprintf(stderr, "ERROR: Invalid command line options\n");
            exit(1);
        }
    }

    if (optind < argc)
    {
        usage();
        fprintf(stderr, "ERROR: Unexpected command line options\n");
        exit(1);
    }

    if (testCaseIndex == 0)
    {
        std::cerr << "example0:" << std::endl;

        if (!example0(filename, refFilename))
        {
            std::cerr << "example0 failed" << std::endl << std::endl;
            return 1;
        }

        std::cerr << "example0 successful" << std::endl;
    }

    return 0;
}


