/*
    Copyright (c) 2016 Edouard M. Griffiths.  All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.
    * Neither the name of CM256 nor the names of its contributors may be
      used to endorse or promote products derived from this software without
      specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
    ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
    LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
    CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
*/

#include <iostream>
#include <fstream>
#include <sys/time.h>

#include "../cm256.h"

long long getUSecs()
{
    struct timeval tp;
    gettimeofday(&tp, 0);
    return (long long) tp.tv_sec * 1000000L + tp.tv_usec;
}

bool example4()
{
#pragma pack(push, 1)
    struct Sample
    {
        uint16_t i;
        uint16_t q;
    };
    struct Header
    {
        uint16_t frameIndex;
        uint8_t  blockIndex;
        uint8_t  filler;
    };

    static const int samplesPerBlock = (512 - sizeof(Header)) / sizeof(Sample);

    struct ProtectedBlock
    {
        Sample samples[samplesPerBlock];
    };
    struct SuperBlock
    {
        Header         header;
        ProtectedBlock protectedBlock;
    };

    struct FileHeader
    {
        cm256_encoder_params m_cm256Params;
        int m_txBlocks;
    };
#pragma pack(pop)

    if (cm256_init())
    {
        return false;
    }

    cm256_encoder_params params;

    // Number of bytes per file block
    params.BlockBytes = sizeof(ProtectedBlock);

    // Number of blocks
    params.OriginalCount = 128;  // Superframe = set of protected frames

    // Number of additional recovery blocks generated by encoder
    params.RecoveryCount = 25;

    SuperBlock txBuffer[256];
    ProtectedBlock txRecovery[256];
    cm256_block txDescriptorBlocks[256];
    int frameCount = 0;

    // Fill original data
    for (int i = 0; i < params.OriginalCount+params.RecoveryCount; ++i)
    {
        txBuffer[i].header.frameIndex = frameCount;
        txBuffer[i].header.blockIndex = i;
        txDescriptorBlocks[i].Block = (void *) &txBuffer[i].protectedBlock;
        txDescriptorBlocks[i].Index = txBuffer[i].header.blockIndex;

        if (i < params.OriginalCount)
        {
            for (int k = 0; k < samplesPerBlock; k++)
            {
                txBuffer[i].protectedBlock.samples[k].i = rand();
                txBuffer[i].protectedBlock.samples[k].q = rand();
            }
        }
        else
        {
            memset((void *) &txBuffer[i].protectedBlock, 0, sizeof(ProtectedBlock));
        }

    }

    // Generate recovery data

    long long ts = getUSecs();

    if (cm256_encode(params, txDescriptorBlocks, txRecovery))
    {
        std::cerr << "example2: encode failed" << std::endl;
        return false;
    }

    long long usecs = getUSecs() - ts;

    std::cerr << "Encoded in " << usecs << " microseconds" << std::endl;

    // insert recovery data in sent data
    for (int i = 0; i < params.RecoveryCount; i++)
    {
        txBuffer[params.OriginalCount+i].protectedBlock = txRecovery[i];
    }

    // puncture blocks to simulate data loss

    SuperBlock* txFileBuffer = new SuperBlock[256]; // received blocks
    int nbTxFileBlocks = 0;

    for (int i = 0; i < params.OriginalCount+params.RecoveryCount; i++)
    {
        if (i % 6 != 4)
        //if (i != 101)
        {
            txFileBuffer[nbTxFileBlocks] = txBuffer[i];
            nbTxFileBlocks++;
        }
    }


    FileHeader fileHeader;
    fileHeader.m_cm256Params = params;
    fileHeader.m_txBlocks = nbTxFileBlocks;

    std::ofstream txFile;
    txFile.open("cm256.test", std::ios::out | std::ios::binary);

    txFile.write((const char *) &fileHeader, sizeof(FileHeader));

    for (int i = 0; i < nbTxFileBlocks; i++)
    {
        txFile.write((const char *) &txFileBuffer[i], sizeof(SuperBlock));
    }

    txFile.close();

    // reference

    std::ofstream refFile;
    refFile.open("ref.test", std::ios::out | std::ios::binary);

    refFile.write((const char *) &fileHeader, sizeof(FileHeader));

    for (int i = 0; i < params.OriginalCount+params.RecoveryCount; i++)
    {
        refFile.write((const char *) &txBuffer[i], sizeof(SuperBlock));
    }

    refFile.close();

    return true;
}


int main()
{
    std::cerr << "example4:" << std::endl;

    if (!example4())
    {
        std::cerr << "example4 failed" << std::endl << std::endl;
        return 1;
    }

    std::cerr << "example4 successful" << std::endl;

    return 0;
}


